apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
  labels:
    app: simple-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: app-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: app-volume
        hostPath:
          path: /path/to/your/project/app
