apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-project
  namespace: k8s-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: nginx:latest
        ports:
        - containerPort: 80
